version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - data:/data/db
  server:
    container_name: server
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    links:
      - mongodb
  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
volumes:
  data: